"""add normalized product name

Revision ID: c45f08a4e27c
Revises: ededcb206b9a
Create Date: 2026-09-14 14:20:19.311344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c45f08a4e27c'
down_revision: Union[str, Sequence[str], None] = 'ededcb206b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "products",
        sa.Column(
            "normalized_name",
            sa.String(),
            nullable=True,
        ),
    )

    op.execute(
        "UPDATE products "
        "SET normalized_name = lower(trim(name))"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'normalized_name')
    # ### end Alembic commands ###
