"""add supplier to products

Revision ID: ededcb206b9a
Revises: e36dda6ae7ff
Create Date: 2026-09-14 13:29:54.403909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ededcb206b9a'
down_revision: Union[str, Sequence[str], None] = 'e36dda6ae7ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('supplier', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'supplier')
    # ### end Alembic commands ###
